package dev.trentdb.execution.ddl;

import dev.trentdb.ast.*; import dev.trentdb.catalog.*; import dev.trentdb.storage.StorageManager; import dev.trentdb.storage.wal.RecoveredTransaction; import dev.trentdb.transaction.*; import dev.trentdb.types.*;
import java.io.*; import java.nio.charset.StandardCharsets; import java.time.LocalDate; import java.util.*;

/** Strict recovery of committed internal DDL/DML WAL intents into an in-memory target. */
public final class DdlWalRecovery {
 private static final int MAX_STRING_BYTES=1<<20; private final Catalog catalog; private final StorageManager storage; private final TransactionManager manager=new TransactionManager(); private final Map<Long,Long> applied=new HashMap<>();
 public DdlWalRecovery(Catalog catalog,StorageManager storage){this.catalog=Objects.requireNonNull(catalog);this.storage=Objects.requireNonNull(storage);}
 public synchronized void replay(List<RecoveredTransaction> transactions){var ordered=new ArrayList<>(transactions);ordered.sort(Comparator.comparingLong(RecoveredTransaction::commitVersion));for(var transaction:ordered)replayOne(transaction);}
 public synchronized Transaction startReadTransaction(){return manager.startTransaction();}
 public synchronized long recoveredCommitVersion(){return manager.committedCatalogVersion();}
 private void replayOne(RecoveredTransaction recovered){Long prior=applied.get(recovered.transactionId());if(prior!=null){if(prior!=recovered.commitVersion())throw new RecoveryException("Transaction id has inconsistent commit version");return;}long expected=manager.committedCatalogVersion()+1;if(recovered.commitVersion()!=expected)throw new RecoveryException("Non-contiguous WAL commit version: "+recovered.commitVersion());var operations=new ArrayList<Operation>();for(byte[] write:recovered.writes())operations.add(decode(write));Transaction transaction=manager.startTransaction();try{for(var operation:operations)apply(transaction,operation);manager.commit(transaction);applied.put(recovered.transactionId(),recovered.commitVersion());}catch(RuntimeException failure){if(transaction.state()==TransactionState.ACTIVE)manager.rollback(transaction);throw failure instanceof RecoveryException?failure:new RecoveryException("Failed to apply WAL transaction "+recovered.transactionId(),failure);}}
 public synchronized void reserveInsertRowIds(List<dev.trentdb.storage.wal.WalRecord> records){for(var record:records){if(record.type()!=dev.trentdb.storage.wal.WalRecordType.WRITE)continue;try{var operation=decode(record.payload());if(operation instanceof Insert insert){try{var table=catalog.lookupTable(manager.startReadTransaction(),new QualifiedName(List.of(insert.schema,insert.table)));storage.reserveNextRowIdAtLeast(table,Math.addExact(insert.rowId,1));}catch(CatalogException ignored){}}}catch(RecoveryException|ArithmeticException ignored){}}}
 private void apply(Transaction tx,Operation operation){switch(operation){case Create create->{var table=catalog.createTable(tx,new QualifiedName(create.name),create.columns);storage.stageCreate(tx,table);}case Drop drop->{var table=catalog.lookupTable(tx,new QualifiedName(drop.name));catalog.dropTable(tx,new QualifiedName(drop.name));storage.stageDrop(tx,table);}case CreateIndex create->catalog.createIndex(tx,new CreateIndexStatement(new QualifiedName(create.name),new QualifiedName(create.tableName),create.keys));case DropIndex drop->catalog.dropIndex(tx,new QualifiedName(drop.name));case Insert insert->applyInsert(tx,insert);case Delete delete->{var table=catalog.lookupTable(tx,new QualifiedName(delete.name));storage.stageDelete(tx,table,delete.rowIds);}case Update update->applyUpdate(tx,update);}}
 private void applyInsert(Transaction tx,Insert insert){var table=catalog.lookupTable(tx,new QualifiedName(List.of(insert.schema,insert.table)));var row=new ArrayList<Object>(Collections.nCopies(table.columns().size(),null));var seen=new HashSet<Integer>();for(var value:insert.values){if(value.ordinal<0||value.ordinal>=table.columns().size()||!seen.add(value.ordinal))throw new RecoveryException("Invalid INSERT column ordinal");var target=table.columns().get(value.ordinal).logicalType();if(target.id()!=value.targetType)throw new RecoveryException("INSERT target type does not match catalog");row.set(value.ordinal,valueFor(value,target));}storage.stageRecoveredAppend(tx,table,row,insert.rowId);}
 private void applyUpdate(Transaction tx,Update update){var table=catalog.lookupTable(tx,new QualifiedName(update.name));var replacements=new ArrayList<dev.trentdb.storage.InMemoryTableStorage.RowReplacement>(update.rows.size());for(var row:update.rows){if(row.values.size()!=table.columns().size())throw new RecoveryException("UPDATE replacement column count does not match catalog");var values=new ArrayList<Object>(row.values.size());for(int ordinal=0;ordinal<row.values.size();ordinal++){var value=row.values.get(ordinal);var target=table.columns().get(ordinal).logicalType();if(value.type!=target.id())throw new RecoveryException("UPDATE value type does not match catalog");values.add(valueFor(new InsertValue(ordinal,target.id(),value.type,value.isNull,value.text),target));}replacements.add(new dev.trentdb.storage.InMemoryTableStorage.RowReplacement(row.rowId,values));}storage.stageUpdates(tx,table,replacements);}

 private Object valueFor(InsertValue value,LogicalType target){if(value.isNull)return null;if(value.literalType==LogicalTypeId.NULL||!assignable(value.literalType,target.id()))throw new RecoveryException("Invalid INSERT literal type");try{Object parsed=switch(value.literalType){case BOOLEAN->parseBoolean(value.text);case INTEGER,BIGINT->Long.parseLong(value.text);case DOUBLE->Double.parseDouble(value.text);case TEXT->value.text;case DATE->LocalDate.parse(value.text);default->throw new RecoveryException("Unsupported INSERT literal type");};if(target.equals(LogicalType.INTEGER))return ((Number)parsed).intValue();if(target.equals(LogicalType.BIGINT))return ((Number)parsed).longValue();if(target.equals(LogicalType.DOUBLE))return ((Number)parsed).doubleValue();return parsed;}catch(IllegalArgumentException failure){throw new RecoveryException("Malformed INSERT literal",failure);}}
 private static boolean assignable(LogicalTypeId source,LogicalTypeId target){return source==target||source==LogicalTypeId.INTEGER&&(target==LogicalTypeId.BIGINT||target==LogicalTypeId.DOUBLE)||source==LogicalTypeId.BIGINT&&target==LogicalTypeId.DOUBLE;}
 private static Boolean parseBoolean(String value){if("true".equals(value))return true;if("false".equals(value))return false;throw new RecoveryException("Malformed boolean literal");}
 private Operation decode(byte[] payload){if(payload==null||payload.length==0)throw new RecoveryException("Empty WAL write payload");try{var in=new DataInputStream(new ByteArrayInputStream(payload));Operation op=switch(in.readUnsignedByte()){case 1->new Create(readName(in),readColumns(in));case 2->new Drop(readName(in));case 3->readInsert(in);case 4->readDelete(in);case 5->readUpdate(in);case 6->readCreateIndex(in);case 7->new DropIndex(readName(in));default->throw new RecoveryException("Unknown WAL operation");};if(in.available()!=0)throw new RecoveryException("Trailing WAL payload bytes");return op;}catch(EOFException failure){throw new RecoveryException("Truncated WAL payload",failure);}catch(IOException|IllegalArgumentException failure){throw new RecoveryException("Malformed WAL payload",failure);}}
 private Insert readInsert(DataInputStream in)throws IOException{String schema=readString(in),table=readString(in);long rowId=in.readLong();if(rowId<=0||rowId==Long.MAX_VALUE)throw new RecoveryException("Invalid row ID");int count=readCount(in);var values=new ArrayList<InsertValue>(count);for(int i=0;i<count;i++){int ordinal=in.readInt();var target=type(in.readInt());var literal=type(in.readInt());boolean nil=in.readBoolean();values.add(new InsertValue(ordinal,target,literal,nil,nil?null:readString(in)));}return new Insert(schema,table,rowId,values);}
 private Delete readDelete(DataInputStream in)throws IOException{var name=readName(in);int count=readCount(in);var ids=new ArrayList<Long>(count);long previous=0;for(int i=0;i<count;i++){long id=in.readLong();if(id<=previous)throw new RecoveryException("Delete row IDs must be sorted");previous=id;ids.add(id);}return new Delete(name,ids);}

 private Update readUpdate(DataInputStream in)throws IOException{var name=readName(in);int count=readCount(in);var rows=new ArrayList<UpdateRow>(count);long previous=0;for(int i=0;i<count;i++){long rowId=in.readLong();if(rowId<=previous)throw new RecoveryException("Update row IDs must be sorted");previous=rowId;int columns=readCount(in);var values=new ArrayList<UpdateValue>(columns);for(int ordinal=0;ordinal<columns;ordinal++){var type=type(in.readInt());boolean nil=in.readBoolean();values.add(new UpdateValue(type,nil,nil?null:readString(in)));}rows.add(new UpdateRow(rowId,values));}return new Update(name,rows);}
 private CreateIndex readCreateIndex(DataInputStream in)throws IOException{var name=readName(in);var table=readName(in);int count=readCount(in);if(count==0)throw new RecoveryException("CREATE INDEX has no keys");var keys=new ArrayList<IndexKey>(count);for(int i=0;i<count;i++){String column=readString(in);int ordinal=in.readUnsignedByte();var directions=SortDirection.values();if(ordinal<0||ordinal>=directions.length)throw new RecoveryException("Invalid index key direction");keys.add(new IndexKey(column,directions[ordinal]));}return new CreateIndex(name,table,keys);}


 private List<ColumnDefinition> readColumns(DataInputStream in)throws IOException{int count=readCount(in);if(count==0)throw new RecoveryException("CREATE TABLE has no columns");var columns=new ArrayList<ColumnDefinition>(count);for(int i=0;i<count;i++)columns.add(new ColumnDefinition(readString(in),TypeName.valueOf(readString(in))));return columns;}
 private List<String> readName(DataInputStream in)throws IOException{int count=readCount(in);if(count<1||count>2)throw new RecoveryException("Invalid qualified name");var parts=new ArrayList<String>(count);for(int i=0;i<count;i++)parts.add(readString(in));return parts;}
 private static int readCount(DataInputStream in)throws IOException{int count=in.readInt();if(count<0||count>100000)throw new RecoveryException("Invalid WAL collection count");return count;}
 private static LogicalTypeId type(int ordinal){var types=LogicalTypeId.values();if(ordinal<0||ordinal>=types.length)throw new RecoveryException("Invalid WAL type id");return types[ordinal];}
 private static String readString(DataInputStream in)throws IOException{int length=in.readInt();if(length<0||length>MAX_STRING_BYTES)throw new RecoveryException("Invalid WAL string length");byte[] bytes=in.readNBytes(length);if(bytes.length!=length)throw new EOFException();String value=new String(bytes,StandardCharsets.UTF_8);if(value.isEmpty())throw new RecoveryException("Empty WAL name/value");return value;}
 private sealed interface Operation permits Create,Drop,CreateIndex,DropIndex,Insert,Delete,Update{} private record Create(List<String> name,List<ColumnDefinition> columns) implements Operation{} private record Drop(List<String> name)implements Operation{} private record CreateIndex(List<String> name,List<String> tableName,List<IndexKey> keys)implements Operation{} private record DropIndex(List<String> name)implements Operation{} private record Insert(String schema,String table,long rowId,List<InsertValue> values)implements Operation{} private record Delete(List<String> name,List<Long> rowIds)implements Operation{} private record Update(List<String> name,List<UpdateRow> rows)implements Operation{} private record UpdateRow(long rowId,List<UpdateValue> values){} private record UpdateValue(LogicalTypeId type,boolean isNull,String text){} private record InsertValue(int ordinal,LogicalTypeId targetType,LogicalTypeId literalType,boolean isNull,String text){}
}
