package dev.trentdb.planner.logical;

public enum LogicalOperatorType {
    LOGICAL_CREATE_TABLE,
    LOGICAL_DROP_TABLE,
    LOGICAL_CREATE_INDEX,
    LOGICAL_DROP_INDEX,
    LOGICAL_INSERT,
    LOGICAL_DELETE,
    LOGICAL_UPDATE,
    LOGICAL_GET,
    LOGICAL_COMPARISON_JOIN,
    LOGICAL_FILTER,
    LOGICAL_PROJECTION,
    LOGICAL_LIMIT,
    LOGICAL_ORDER_BY,
    LOGICAL_AGGREGATE_AND_GROUP_BY,
    LOGICAL_DELIM_JOIN,
    LOGICAL_EXPLAIN,
    LOGICAL_UNION,
    LOGICAL_UNION_ALL,
    LOGICAL_EXCEPT,
    LOGICAL_INTERSECT
}
