package dev.trentdb.storage;
import dev.trentdb.storage.format.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class DuckDbTableStatisticsReaderTest{@TempDir Path d;
@Test void goldenAndDefaultNullOnly(){try(var m=file("g",stats(13,1,1,7,true,2,true,9))){var s=new DuckDbTableStatisticsReader(m,MetaBlockPointer.of(0,0,0),List.of(DuckDbTableCreateInfo.ScalarLogicalType.INTEGER)).read().columns().get(0);assertEquals(OptionalLong.of(2),s.min());assertEquals(OptionalLong.of(9),s.max());assertEquals(7,s.distinctCount());}try(var m=file("n",stats(13,1,0,0,false,0,false,0))){var s=new DuckDbTableStatisticsReader(m,MetaBlockPointer.of(0,0,0),List.of(DuckDbTableCreateInfo.ScalarLogicalType.INTEGER)).read().columns().get(0);assertTrue(s.min().isEmpty());assertTrue(s.max().isEmpty());}}
@Test void rejectsMismatchUnsupportedSampleAndTruncation(){fail(new byte[]{100,0,0,(byte)255,(byte)255},List.of(DuckDbTableCreateInfo.ScalarLogicalType.INTEGER),"DuckDB TableStatistics column count mismatch");fail(stats(25,0,0,0,false,0,false,0),List.of(DuckDbTableCreateInfo.ScalarLogicalType.VARCHAR),"DuckDB TableStatistics logical type is unsupported: VARCHAR");fail(new byte[]{100,0,0,101,0},List.of(),"DuckDB TableStatistics sample field 101 is unsupported");fail(new byte[]{100,0,1,100,0,1},List.of(DuckDbTableCreateInfo.ScalarLogicalType.INTEGER),"DuckDB binary metadata field mismatch: expected 101 but found 0");}
void fail(byte[] p,List<DuckDbTableCreateInfo.ScalarLogicalType> t,String x){try(var m=file("x"+System.nanoTime(),p)){var e=assertThrows(StorageFormatException.class,()->new DuckDbTableStatisticsReader(m,MetaBlockPointer.of(0,0,0),t).read());assertEquals(x,e.getMessage());}}
byte[] stats(int ty,int hn,int hnn,int d,boolean hp,int min,boolean hq,int max){java.io.ByteArrayOutputStream b=new java.io.ByteArrayOutputStream();int[] h={100,0,1,100,0,hn,101,0,hnn,102,0,d,103,0};for(int x:h)b.write(x);bound(b,200,hp,min);bound(b,201,hq,max);for(int i=0;i<4;i++){b.write(255);b.write(255);}return b.toByteArray();}
void bound(java.io.ByteArrayOutputStream b,int id,boolean present,int value){b.write(id);b.write(0);b.write(100);b.write(0);b.write(present?1:0);if(present){b.write(101);b.write(0);b.write(value);}b.write(255);b.write(255);}

SingleFileBlockManager file(String n,byte[] p){var q=d.resolve(n);try(var w=SingleFileBlockManager.create(q,new byte[16])){var b=new byte[w.usableBlockSize()];for(int i=0;i<8;i++)b[i]=(byte)(MetaBlockPointer.INVALID_BLOCK_POINTER >>>8*i);System.arraycopy(p,0,b,8,p.length);w.writeBlock(0,b);}return SingleFileBlockManager.openMetadataReadOnly(q);}}
